finished Session5
yumemi-inc/iOS-training-Kotaro pull request #3
Opened 2023-07-11 06:43 UTC by Kota1021

https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md

の仕様にあった「呼び出しAPIをThrows verに変更する」に関しては調べましたが、
Throws ver
の意味がよく分かりませんでした。
ただしエラーを切り分けることはできているかと思います。

2023-07-12 07:52 UTC, ruby109 commented on iOS-training/LayoutPrototype.swift
> +        }
```suggestion
        } catch let error. as YumemiWeatherError {
            return WeatherFetchResult.failure(error)
        } catch {
        //blablabla
        }
```

2023-07-12 07:59 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +        }
ありがとうございます！
いただいたご提案を実装しました！

2023-07-13 01:00 UTC, myihsan requested changes

2023-07-13 03:16 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +        .alert("Error", isPresented: .constant(errorAlertIsPresented)) { /* Buttons */ } message: {
```Binding(get: _, set: _)```
を使用するように変更しました！

2023-07-13 03:16 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +enum WeatherFetchResult {
```Result<Weather, Error>```
を使用するように変更しました！

2023-07-13 03:18 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +            fatalError("LayoutPrototype: fetchWeatherCondition(at:) returned invalid error \(error)")
```.failure(YumemiWeatherError.unknownError)```
に変更しました！

2023-07-13 03:18 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +        .alert("Error", isPresented: .constant(errorAlertIsPresented)) { /* Buttons */ } message: {
バッチリです👍

2023-07-13 03:21 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +    case failure(YumemiWeatherError)
```Result<String, Error> { try YumemiWeather.fetchWeatherCondition(at: area) )```
を使用することで、少しシンプルなコードになりました。

2023-07-13 03:25 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +    case failure(YumemiWeatherError)
@Kota1021 
> Resultのドキュメントを確認してみてください。

Resultのinitはバッチリです。

ただ`Result<Weather, Error>`に変換する方にも使いやすいAPIがありますので、もうちょっと調べてみてください。

2023-07-13 04:11 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +    case failure(YumemiWeatherError)
アドバイスありがとうございます。
調べたところ、以下の四つのAPIがいただいたヒントに近いと思いました。
```map<NewSuccess>((Success) -> NewSuccess) -> Result<NewSuccess, Failure>```
```mapError<NewFailure>((Failure) -> NewFailure) -> Result<Success, NewFailure>```
```flatMap<NewSuccess>((Success) -> Result<NewSuccess, Failure>) -> Result<NewSuccess, Failure>```
```flatMapError<NewFailure>((Failure) -> Result<Success, NewFailure>) -> Result<Success, NewFailure>```

しかし、今回の実装では、fetchWeatherCondition(at:)が不正な文字列を返した場合にエラーを返しており、mapなどを使うとさらに面倒そうでした。
さらに良い方法はありますでしょうか？
<img width="788" alt="スクリーンショット 2023-07-13 13 08 44" src="https://github.com/yumemi-inc/iOS-training-Kotaro/assets/9388824/710d642c-aaff-4802-b693-6d326ea154c7">

2023-07-13 05:09 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +    case failure(YumemiWeatherError)
大差はないかもしれませんが、この場合において`flatMap<NewSuccess>((Success) -> Result<NewSuccess, Failure>) -> Result<NewSuccess, Failure>`がちょうどいいと思いますが、使ってみましょうか。

2023-07-13 05:29 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +    case failure(YumemiWeatherError)
ありがとうございます。
flatMapを使用しました。
よろしくお願いします。

2023-07-13 05:46 UTC, myihsan approved these changes
細かい一点コメントしましたが、全体的にLGTMです。
対応ありがとうございます！

2023-07-13 05:46 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +            }
![badge](https://img.shields.io/badge/review-nits-green.svg)
`buildIf(_:)`がサポートされていますので、if case文法使うと、`EmptyView()`書く必要もなくなりそうです。

また
```swift
func alert<E, A, M>(isPresented: Binding<Bool>, error: E?, @ViewBuilder actions: (E) -> A, @ViewBuilder message: (E) -> M) -> some View where E : LocalizedError, A : View, M : View
```
というerrorをアンラップしてくれるAPIもあります。
ただこの場合タイトルもerrorによって決められて、使い勝手が良くないので、あくまで共有です。

2023-07-13 05:58 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +            }
ご提案ありがとうございます。
実は、```if case```も書いてみたのですが、weatherFetchResultはoptionalなので、
```if let weatherFetchResult, case...```
と長くなったので、今回はこちらにしました！

そのようなAlertもあるのですね！ありがとうございます。

2023-07-13 05:59 UTC, merged

2023-07-13 05:59 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +            }
`if case`で書いてみてください。

2023-07-13 08:15 UTC, Kota1021 commented
> `Throws ver` はエラーをThrowしてくれるversionの関数のことだと思います💦

ありがとうございます笑笑
こんな変数があるのか（？）と調べていました。
承知しました。