Session6
yumemi-inc/iOS-training-Kotaro pull request #4
Opened 2023-07-13 05:28 UTC by Kota1021

session6 JSON
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md

session7 Codable
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Codable.md

session6の範囲はJSONだけですが、session6で既にCodable protocolに関する処理（session7に該当）をしているので、両方に対応するブランチとしてリクエストします。

よろしくお願いします🔥

2023-07-14 00:52 UTC, yuk1ch1 commented on iOS-training/LayoutPrototype.swift
> +    @State private var weatherFetchResult: Result<WeatherAPIClient.WeatherDateTemperature, Error>?
[imo]
WeatherAPIClient.WeatherDateTemperatureというように長くなってしまっています
面倒かと思いますし、ここではWeatherDateTemperatureを使いたいだけだと思うので
WeatherDateTemperature自体をWeatherAPIClient内に書くのではなくて外に出してみてはどうでしょうか？

2023-07-14 00:56 UTC, myihsan requested changes

2023-07-14 00:56 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +                    Text(weatherInfo != nil ? "\(weatherInfo!.maxTemperature)" : "--")
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
`weatherInfo != nil`2回やっていて、フォースアンラップもしていて、あまりよろしくないですね。

1. フォースアンラップしない（ヒント：`Optional`のAPI）
2. weatherInfoが値あるかどうかのチェックを一回に

↑から順で試してみましょう。
後者やると前者いらないですが、フォースアンラップ回避する方法としてしておくといいと思います。

2023-07-14 00:56 UTC, myihsan commented on iOS-training/LayoutPrototype.swift
> +                        print("reload tapped")
![badge](https://img.shields.io/badge/review-must-red.svg)
デバッグ用のものは残さないでください。
ログとして残したい場合は
https://developer.apple.com/documentation/os/logger
こういうものがあります。

2023-07-14 00:56 UTC, myihsan commented on iOS-training/Models/JSONConverter.swift
![badge](https://img.shields.io/badge/review-ask-blue.svg)
不要なファイル？

2023-07-14 00:56 UTC, myihsan commented on iOS-training/Models/Weather.swift
> +import SwiftUI
![badge](https://img.shields.io/badge/review-nits-green.svg)
Modelとして切り出しているとしたら、View側の都合を持ち込まない方が理想で、SwiftUIをimportしない方法検討してみましょうか。

2023-07-14 00:56 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +        }
![badge](https://img.shields.io/badge/review-nits-green.svg)
`print`のためにこうなっているかと思いますが、`Result`のAPI使いましょう。

2023-07-14 00:56 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
![badge](https://img.shields.io/badge/review-must-red.svg)
フォースアンラップとfatalErrorを適切に無くしてください。

2023-07-14 00:56 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +        // しかし、dateEncodingStrategyでiso8601を指定すると末尾にzが着く
![badge](https://img.shields.io/badge/review-imo-orange.svg)
この二行のコメントはすでにお互いに矛盾してますね。
末尾にzが付くことが許されてない仕様だったら、もうISO8601ではなくなりますね。
（朝会でちょっと話そうか）

2023-07-14 00:56 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +        }
![badge](https://img.shields.io/badge/review-nits-green.svg)
これでもいいですが、今の`YumemiWeather`使用上、もう一ついちいち定義しなくてもいい方法があって、`JSONDecoder`のドキュメントを探ってみてください。

2023-07-14 00:59 UTC, yuk1ch1 commented on iOS-training/Models/WeatherAPIClient.swift
> +            case weatherCondition = "weather_condition"
[imo]
単にスネークケースからキャメルケースへの変換であれば自動で行ってくれるAPIがJSONDecoderに存在しているので調べてみてください

2023-07-14 01:10 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +    @State private var weatherFetchResult: Result<WeatherAPIClient.WeatherDateTemperature, Error>?
ありがとうございます。
外に出しました。

2023-07-14 01:20 UTC, Kota1021 commented on iOS-training/LayoutPrototype.swift
> +                        print("reload tapped")
ありがとうございます。
削除しました！

2023-07-14 04:31 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        // しかし、dateEncodingStrategyでiso8601を指定すると末尾にzが着く
ありがとうございます。
APIがISO8601に準拠していないので、それに合わせてハードコーディングをすることにしました。

2023-07-14 04:56 UTC, Kota1021 commented on iOS-training/Models/Weather.swift
> +import SwiftUI
新たにWeatherIcon Viewを作成し、Weather modelはSwift標準ライブラリのみを知る（何もimportしない）ようにしました。

2023-07-14 04:59 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +            case weatherCondition = "weather_condition"
keyDecodingStrategy = .convertFromSnakeCase
を導入しました

2023-07-14 04:59 UTC, yuk1ch1 reviewed
細かいですが追加でコメントさせてもらいました

2023-07-14 04:59 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        }
keyDecodingStrategy = .convertFromSnakeCase
を導入しました

2023-07-14 05:01 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        print("fetchWeatherCondition called")
削除しました！

2023-07-14 05:18 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        }
Result.init(catching:) を使用するよう変更しました

2023-07-14 06:18 UTC, Kota1021 commented on iOS-training/Models/JSONConverter.swift
ご指摘いただいたJSONConverter.swiftを削除し、forcepushしました。

2023-07-14 06:19 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
ありがとうございます。
エラーをthrowするようにしました。

2023-07-14 06:25 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        let weatherCondition: Weather
ご提案ありがとうございます。
気になって調べたところ2016年と少し古いarticleになりますが、appleは以下のような書き方をしていたので、そちらを参考に修正しました。

```
// Example JSON with object root
/*
    {
       "max_temperature":25,
       "date":"2020-04-01T12:00:00+09:00",
       "min_temperature":7,
       "weather_condition":"cloudy"
    }
*/
```
https://developer.apple.com/swift/blog/?id=37

2023-07-18 00:56 UTC, myihsan requested changes

2023-07-18 00:56 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +            preconditionFailure("could not encode areaDate")
https://www.swiftbysundell.com/articles/under-the-hood-of-assertions-in-swift/
前に共有した記事ではこれだけ足りませんでした💦
合わせて見て何を使うか検討しみてください。

2023-07-18 00:56 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +            return String(data: areaDateJSONData, encoding: .utf8)!
![badge](https://img.shields.io/badge/review-must-red.svg)
こちらのフォースアンラップもなくしてください。
現時点では問題ないかもしれませんが、実際の開発において、途中に変更を入れることで、気づきにくいクラッシュが発生する可能性があるためです。

2023-07-18 00:56 UTC, myihsan commented on iOS-training/Models/WeatherDateTemperature.swift
> +    let date: Date // ISO 8601
![badge](https://img.shields.io/badge/review-nits-green.svg)
前に話した通りで、ISO 8601と近いけど違うので、このコメント無くしましょうか。

2023-07-18 00:56 UTC, myihsan commented on iOS-training/WeatherIcon.swift
> +            (Image(systemName: "exclamationmark.square.fill"), .gray)
![badge](https://img.shields.io/badge/review-ask-blue.svg)
初期状態でもエラーのように見えますが、意図的でしょうか？
（明確な仕様がないので、意図的にした場合は問題ない）

2023-07-18 00:57 UTC, r0ar-69 commented on iOS-training/Models/WeatherAPIClient.swift
> +            return String(data: areaDateJSONData, encoding: .utf8)!
[must]
ここもforce unwrappingは極力避けましょう。`guard let`で`nil`を弾いてcatch節に流したりするといいかなと思います。

2023-07-18 00:58 UTC, r0ar-69 commented on iOS-training/Models/WeatherAPIClient.swift
> +            return String(data: areaDateJSONData, encoding: .utf8)!
李さんと被ってしまったのでResolveにしておきます💦c

2023-07-18 01:01 UTC, Kota1021 commented on iOS-training/Models/WeatherDateTemperature.swift
> +    let date: Date // ISO 8601
削除しました

2023-07-18 01:05 UTC, yuk1ch1 commented
自分からは特にないです
formatterを変数にしたのでいいと思います
少しコメントが多いなという印象ですが、適切に変数名をつけることでカバーできるものもあるので
その辺をもう少し意識すればある程度消せるかなという印象です

2023-07-18 01:11 UTC, yuk1ch1 commented on iOS-training/Models/WeatherAPIClient.swift
> +        let weatherCondition: Weather
[iimo]
んー送っていただい参考情報はmodel定義のところじゃなくてどのようなJSON構造からわからないからなんですかね？

ここは明らかに構造わかりますし、ファイルが膨らんで見づらくなるので不要だと思うのであれば消したほうがいいと思います

2023-07-18 03:00 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        let weatherCondition: Weather
ご説明ありがとうございます。
削除しました。

2023-07-18 03:01 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +            return String(data: areaDateJSONData, encoding: .utf8)!
ありがとうございます。
nilの場合はJSONErrorを投げるように変更しました。

2023-07-18 03:02 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +            preconditionFailure("could not encode areaDate")
ありがとうございます。
JSONErrorを投げるように変更しました。

2023-07-18 03:08 UTC, Kota1021 commented on iOS-training/WeatherIcon.swift
> +            (Image(systemName: "exclamationmark.square.fill"), .gray)
ご指摘ありがとうございます。
こちらは簡略化のために意図された実装です。

2023-07-18 03:34 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +        case encodedIntoNil
![badge](https://img.shields.io/badge/review-ask-blue.svg)
名前に違和感というか、分かりにくいと感じますね。
英語の問題かそもそも私が松本さんが表したいこと理解できてないか問題を切り分けるために、日本語だったらどうなるか教えてください。

2023-07-18 03:34 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +    }
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
似たようなメソッドだけど、方針のブレを感じますね。どちらかに統一しましょうか。
JSONDecoder/Encoderのエラーを
- そのままthrows
- キャッチして、自前のエラーにしてthrows

2023-07-18 03:43 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +    }
ご指摘ありがとうございます。
JSONDecoder/Encoderのエラーをそのままthrowするように統一しました。

2023-07-18 03:47 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +        case encodedIntoNil
ご指摘ありがとうございます。
failedToStringify：
JSONのData型をString型に変更することに失敗
encodedIntoNil：
エンコードしたJSONのData型をString型に変更することに失敗

と同じことを表現していることに気がついたため、encodedIntoNilを削除しました。

2023-07-18 05:57 UTC, myihsan reviewed
対応ありがとうございます！
一旦研修課題最後のPRになるかもしれませんので、他のメンバーのapproveも待っていただければと思います。

2023-07-18 05:57 UTC, myihsan commented on iOS-training/Models/WeatherAPIClient.swift
> +            return weatherDateTemperature
![badge](https://img.shields.io/badge/review-nits-green.svg)
Indentずれてます。

2023-07-18 05:57 UTC, myihsan approved these changes
↑と言いながらapproveすることに忘れました。

2023-07-18 06:00 UTC, Kota1021 commented on iOS-training/Models/WeatherAPIClient.swift
> +            return weatherDateTemperature
ご指摘ありがとうございます。
まだSwiftLint導入前で、手作業でformatしており、抜けがありました🙇‍♂️

2023-07-19 03:10 UTC, kiy00 approved these changes
ごめんなさい、approveしてなかったです💦LGTM!!

2023-07-19 03:18 UTC, yuk1ch1 commented
自分の方権限がないのか特にapproveできないので
[こちら](https://github.com/yumemi-inc/iOS-training-Kotaro/pull/4#issuecomment-1639119932)のコメントを持ってapproveとさせてください

2023-07-20 01:14 UTC, merged